// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GameController from "./game_controller"
application.register("game", GameController)

import RequestFormController from "./request_form_controller"
application.register("request-form", RequestFormController)

import ListSelectorController from "./list_selector_controller"
application.register("list-selector", ListSelectorController)

import FavoriteModalController from "./favorite_modal_controller"
application.register("favorite-modal", FavoriteModalController)