// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardSetFormController from "./card_set_form_controller"
application.register("card-set-form", CardSetFormController)
